# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-Services-Daemon
version:      0.08
version_from: perfsonar
installdirs:  site
requires:
    base:                          0
    Config::General:               2.3
    Cwd:                           0
    English:                       0
    Error:                         0
    Fcntl:                         0
    fields:                        0
    File::Basename:                0
    File::Temp:                    0
    Getopt::Long:                  0
    HTTP::Daemon:                  1.35
    lib:                           0
    Log::Dispatch::FileRotate:     1
    Log::Dispatch::Screen:         1
    Log::Dispatch::Syslog:         1
    Log::Log4perl:                 1
    Module::Load:                  0.1
    Params::Validate:              0.7
    perfSONAR_PS::Common:          0.08
    perfSONAR_PS::Error:           0.08
    perfSONAR_PS::Error_compat:    0.08
    perfSONAR_PS::Messages:        0.08
    perfSONAR_PS::XML::Document_string: 0.08
    POSIX:                         0
    strict:                        0
    Sys::Hostname:                 0
    Time::HiRes:                   1.85
    warnings:                      0
    XML::LibXML:                   1.58

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
